### ISSUE TITLE
Icons not show in dokuwiki current stable version

### ISSUE THREAD

**Issue by optiwiper** [orangain/dokuwiki-copypage-plugin#7]
Hi,

I am using dokuwiki stable version (2017-02-19e "Frusterick Manners") with the default theme and the copypage icons are not show. I can not find the reason, can you help? Attached screenshot.

I translated the pluguin into Spanish, do you want to add this language? Indicate where to upload the lan.php file.

Excuse for my bad English.
Greetings.

![dokuwiki_copypage_err](https://user-images.githubusercontent.com/16511280/31908955-df2470fc-b838-11e7-9e63-d661e9c24004.png)

**Comment by orangain** [comment]
Unfortunately, I can't reproduce the problem you said. In my environment, Dokuwiki 2017-02-19e and default theme, the icon is shown as expected.

If your Dokuwiki is accessible from the Internet, please tell me the URL (if you worry, email to orangain@gmail.com). Otherwise, I would like to ask you some questions.

1. What kind and version of browser do you use? 
2. Open a developer tool of your browser (e.g. https://developers.google.com/web/tools/chrome-devtools/console/). Is there any error in console or network tab when you open your Dokuwiki page?

---

Spanish translation is very welcome! Please just paste content of lang.php in a comment of this issue.

**Comment by optiwiper** [comment]
It works now!
I found a directory with incorrect permissions (I'm stupid). His plugin is perfect for now, without errors. I was the mistake. Thanks for your suggestions, they have been very helpful.

One doubt, these entries must be translated?

// $lang['menu'] = 'Your menu entry';
// $lang['fixme'] = 'FIXME';


Thank you very much for your time.
Regards.

**Comment by orangain** [comment]
I'm glad to hear that!

> these entries must be translated?

No. They are just example of translation. Please leave them as they are.

**Comment by optiwiper** [comment]
Hi, attached ZIP file with the translations, es_ES and ca_ES.
Greetings.

[dokuwiki-copypage-plugin_new-lang_011117.zip](https://github.com/orangain/dokuwiki-copypage-plugin/files/1435143/dokuwiki-copypage-plugin_new-lang_011117.zip)

**Comment by orangain** [comment]
Thanks a lot! I've released new version 2017-11-02 of [the plugin](https://www.dokuwiki.org/plugin:copypage) which includes your translations. Please try it out.
